# Same voxel IDs from blocklightColor.glsl
item.2 = torch wall_torch lantern
item.3 = glowstone
item.4 = sea_lantern
item.5 = lava_bucket
item.6 = campfire
item.7 = redstone_torch redstone_wall_torch
item.8 = jack_o_lantern
item.9 = furnace
item.10 = magma_block
item.11 = soul_torch soul_wall_torch soul_lantern soul_campfire
item.12 = crying_obsidian
item.14 = end_rod
item.15 = shroomlight
item.16 = beacon
item.17 = ochre_froglight
item.18 = verdant_froglight
item.19 = pearlescent_froglight
item.26 = copper_torch copper_wall_torch