# Photonics
photonics.enabled=PHOTONICS_ENABLED
photonics.lightingMode=restir
photonics.restirCombinedGi=false
photonics.restirSoftShadows=true
photonics.enableHandheldLight=true

# Custom Uniforms
uniform.float.PI=3.14159265

# Minecraft Options
underwaterOverlay=false
oldLighting=false
vignette=false

particles.before.deferred = true
dynamicHandLight=true
separateAo=false
frustum.culling=true
shadow.culling=true
shadowDistanceRenderMul=1.0
program.shadow.enabled=shadowMap

alphaTest.gbuffers_water=GREATER 0.01
alphaTest.gbuffers_weather=GREATER 0.0001
beacon.beam.depth=true

# Voxel Settings
iris.features.required=CUSTOM_IMAGES
voxelizeLightBlocks=true
image.voxel_img=voxelSampler red_integer r8ui unsigned_int true false 128 64 128
image.floodfill_img=floodfillSampler rgba rgba16f half_float false false 128 64 128
image.floodfill_img_copy=floodfillSamplerCopy rgba rgba16f half_float false false 128 64 128
program.world0/shadowcomp.enabled=true

shadowHardwareFiltering0 = true
shadowHardwareFiltering1 = true

# Sliders
sliders= SSS_Quality reflectedCausticsStrength VC_STEPS VC_REFL_STEPS VC_MAX_STEP VC_LIGHT_STEPS VC_CLOUD_BOTTOM VC_CLOUD_TOP VC_COVERAGE VC_DENSITY VC_SIZE VC_SUN_BRIGHTNESS VC_AMBIENT VC_WIND_SPEED caveFogStrength emissionStrength parallaxNearDist aoQuality aoStrength exposure parallaxQuality parallaxShadowDepth CLOUD_FOG_SAMPLES AbsorptionCoeffR AbsorptionCoeffG AbsorptionCoeffB deepwaterR deepwaterG deepwaterB shallowwaterR shallowwaterG shallowwaterB shadowDistortion shadowDistance PBRReflectionStr parallaxDepth parallaxFarDist parallaxShadowQuality parallaxShadowStrength Focal torchR torchG torchB bounceQuality aoRadius grassHeight lightingQuality colorTemperature LUTstrength filmGrain saturation SharpenStr FogStrength FogAltitude shadowMapResolution sunPathRotation filterStr min_skyLightMap lightStr ambientStr BounceAmbient BounceLightStr SunlightContribution BounceLightContribution pstrength pshininess volumetricFogQuality

# Main screen
screen= <empty> <empty> <profile> <empty> <empty> <empty> [LightMap] [Lighting] [Atmosphere] [Post] [Materials] [Reflections] [WaterColors] wavingFoliage <empty> <empty> <empty> [misc]
# Sub-screen
screen.LightMap= <empty> <empty> shadowMapResolution sunPathRotation torchLightMap [torchColors] skyLightMap
	screen.torchColors = <empty> <empty> torchR <empty> torchG <empty> torchB

screen.Lighting= <empty> <empty> [AO] VoxelLighting [FillLight] SubsurfaceScattering <empty> SSS_Quality <empty> <empty> shadowDistance lightingQuality lightStr min_skyLightMap filterStr ambientStr
	screen.AO = <empty> <empty> AO <empty> <empty> <empty> aoQuality <empty> aoRadius <empty> aoStrength
	screen.FillLight= <empty> <empty> BounceLight BounceColoredLight bounceQuality BounceLightStr

screen.Atmosphere= <empty> <empty> [VolumetricClouds] [VolumetricLight] <empty> <empty> Fog atmosphereFog <empty> <empty> fogBlur rainfogBlur BorderFog <empty> <empty> <empty> caveFog caveFogStrength
	screen.VolumetricLight= <empty> <empty> volumetricLight <empty> <empty> <empty> volumetricFogQuality FogAltitude FogStrength
	screen.VolumetricClouds= <empty> <empty> VolumetricClouds VC_REFLECTIONS <empty> <empty> [CloudQuality] [CloudParameters]
		screen.CloudQuality= <empty> <empty> # WIP
		screen.CloudParameters= <empty> <empty> # WIP

screen.Post= <empty> <empty> <empty> <empty> [ToneMap] TAA [Depth_of_Field] BLOOM PURKINJE_SHIFT screenSunGlare
	screen.ToneMap= <empty> <empty> ToneMap exposure <empty> <empty> tonemapSaturation saturation FilmGrain filmGrain colorTemp colorTemperature inverseKaris
	screen.Depth_of_Field= <empty> <empty> DOF Focal

screen.Materials= <empty> <empty> CookTorranceGGXBRDF materialReflections <empty> <empty> Parallax parallaxTAA parallaxQuality parallaxDepth parallaxFarDist <empty> ParallaxShadow [ShadowSettings] <empty> <empty> materialEmission emissionStrength
	screen.ShadowSettings= <empty> <empty> parallaxShadowQuality parallaxShadowDepth parallaxShadowStrength

screen.Reflections = <empty> <empty> ParallaxWater <empty> <empty> <empty> Caustics <empty> reflectedCaustics reflectedCausticsStrength <empty> <empty> rainReflection
screen.WaterColors= <empty> <empty> shallowwaterR deepwaterR shallowwaterG deepwaterG shallowwaterB deepwaterB <empty> <empty> AbsorptionCoeffR <empty> AbsorptionCoeffG <empty> AbsorptionCoeffB

screen.misc= <empty> <empty> whiteWorld alwaysPuddles grassHeight

# screen.Mods= <empty> <empty> PHOTONICS_ENABLED

# Profiles

profile.Low= aoQuality=2 CLOUD_FOG_SAMPLES=3 bounceQuality=2 !Caustics !reflectedCaustics !AO !fogBlur shadowMapResolution=1536 lightingQuality=2 filterStr=0.40 BounceLight !BounceColoredLight volumetricFogQuality=3 !ParallaxWater !BLOOM screenSunGlare
# The original Default profile that was replaced with the old high profile, the performance difference was 3-4%, no reason to have profiles that close in performance
# profile.Default= aoQuality=2 CLOUD_FOG_SAMPLES=6 bounceQuality=2 Caustics reflectedCaustics AO fogBlur shadowMapResolution=1536 lightingQuality=2 filterStr=0.30 BounceLight BounceColoredLight volumetricFogQuality=4 ParallaxWater BLOOM !screenSunGlare
profile.Default= aoQuality=2 CLOUD_FOG_SAMPLES=6 bounceQuality=4 Caustics reflectedCaustics AO fogBlur shadowMapResolution=2048 lightingQuality=2 filterStr=0.30 BounceLight BounceColoredLight volumetricFogQuality=8 ParallaxWater BLOOM !screenSunGlare
profile.High= aoQuality=4 CLOUD_FOG_SAMPLES=8 bounceQuality=4 Caustics reflectedCaustics AO fogBlur shadowMapResolution=4096 lightingQuality=4 filterStr=0.15 BounceLight BounceColoredLight volumetricFogQuality=8 ParallaxWater BLOOM !screenSunGlare